input {
  file {
    path => "/usr/share/logstash/cash-registers/*.csv"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => "plain"
  }
}

filter {
  csv {
    separator => ","
    columns => ["timestamp","shop_id","order_id","product_id","quantity","price"]
  }

  mutate {
    convert => { "quantity" => "integer" }
    convert => { "price" => "float" }
  }

  # Elimina tutto il resto e lascia solo i campi desiderati
  mutate {
    remove_field => ["@version","@timestamp","host","message","log","event"]
  }

  # Scarta l'header CSV
  if [order_id] == "order_id" {
    drop { }
  }
}

output {
  kafka {
    bootstrap_servers => "broker:9092"
    topic_id => "super-cash-stream"
    codec => "json"
  }
}
